package exceptionHandling;

public class ThrowDemo1 {

	public static void main(String[] args) {
		System.out.println(10/0);

	}

}

/*Exception in thread "main" java.lang.ArithmeticException: / by Zero
at exceptionHandling.ThrowDemo2.main(ThrowDemo2.java:6)*/
